#!/usr/bin/env bash
# script to install and setup nginx

CONFIG_FILE="/etc/nginx/sites-available/default"
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World' > /usr/share/nginx/html/index.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /usr/share/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > $CONFIG_FILE
service nginx start
