#!/usr/bin/env bash
# Install your load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend estebanweb
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 189256-web-01 54.236.43.3:80 check
    server 189256-web-02 100.25.38.88:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
