#!/usr/bin/env bash
#Process and PID file
echo "$$" > /var/run/myscript.pid
trap '{echo "I hate the kill command"; rm -f /var/run/myscript.pid;}' SIGTERM
trap '{echo "Y U no love me?!"; exit 1;}' SIGINT
trap 'rm -f /var/run/myscript.pid' SIGQUIT
while true; do
        echo "To infinity and beyond"
done
