#!/usr/bin/env bash
# displays Best School 10 times
i=0
end=10
while ((i < end)); do
	if [ $i -eq 3 ] ; then
		echo "bad luck"
	elif [ $i -eq 7 ] ; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
